theme = "dark-synthwave"
[editor]
mouse = false
cursorline = true
cursorcolumn = true
default-line-ending = "lf"
continue-comments = false
bufferline = "always"
color-modes = true
popup-border = "all"

[editor.lsp]
display-messages = false
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "hint" # エラーメッセージなどをインラインにする

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
[keys.insert]
j = { k = "normal_mode" }
