[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server", # optional
  "vscode-eslint-language-server",
]
[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "python"
language-servers = [ "pyright","ruff" ]
auto-format = true

[[language]]
name = "csharp"
scope = "source.cs"
file-types = ["cs"]
roots = ["*.slnx", "*.sln", "*.csproj"]
language-servers = [ "csharp-ls" ]

[language-server.csharp-ls]
command = "csharp-ls"

[[language]]
name = "c"
scope = "source.c"
language-servers = ["clangd"]

[[language]]
name = "cpp"
file-types=["cpp","ino","cxx","h","hpp"]
roots=["sketch.yaml","sketch.json",".git"]
language-servers = [""]

# [language-server.arduino-lsp]
# command = "arduino-language-server"
# args = [
#   "-cli", "arduino-cli",
#   "-clangd","clangd",
#   "-fqbn", "arduino:renesas_uno:unor4wifi",
#   "-cli-config", "/home/ritsu/.arduino15/arduino-cli.yaml"
# ]

