[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server", # optional
  "vscode-eslint-language-server",
]
[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "python"
language-servers = [ "pyright","ruff" ]
auto-format = true

[[language]]
name = "csharp"
scope = "source.cs"
file-types = ["cs"]
roots = ["*.slnx", "*.sln", "*.csproj"]
language-servers = [ "csharp-ls" ]

[language-server.csharp-ls]
command = "csharp-ls"

[[language]]
name = "c"
scope = "source.c"
language-servers = ["clangd"]

[[language]]
name = "cpp"
scope = "source.cpp"
file-types=["c","ino","cxx","h","hpp","ino"]
roots=["sketch.yaml","arduino-cli.yaml","sketch.json",".git"]
language-servers = ["clangd"]

# [language-server.arduino-lsp]
# command="arduino-language-server"
# args = [
#     "-clangd", "clangd",
#     "-cli", "arduino-cli",
#     "-cli-config", "/home/YOUR_USER/.arduino15/arduino-cli.yaml", # パスは環境に合わせて修正
#     "-fqbn", "arduino:renesas_uno:wifi"
# ]

# [[language]]
# name = "arduino"
# scope="source.cpp"
# file-type=["ino","cxx","h","hpp","ino"]
# roots=["sketch.yaml","arduino-cli.yaml","sketch.json",".git"]
# language-servers=["aruduino-lsp"]
